name: Enforce timeout-minutes

on: push

jobs:
  enforce-timeout-minutes:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Enforce timeout-minutes
        id: enforce-timeout-minutes
        uses: komiya-atsushi/action-enforce-timeout-minutes@v1

      - name: Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: ${{ steps.enforce-timeout-minutes.outputs.message }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() }}
